### ISSUE TITLE
session ls crashes server

### ISSUE THREAD

**Issue by cnf** [moul/sshportal#50] opened 2018-03-04 16:02 UTC
**What happened**:
typed `session ls` on the `config>` prompt, and the server crashed.

**What you expected to happen**:
to get a list of sessions.

**How to reproduce it (as minimally and precisely as possible)**:
Run v1.7.1 in docker, create an admin user, type `session ls`

**Anything else we need to know?**:
```
config> info
Debug mode (server): false
Hostname: remote-access-sshportal-1
CPUs: 1
Demo mode: false
DB Driver: sqlite3
DB Conn: ./sshportal.db
Bind Address: :2222
System Time: 2018-03-04T16:01:29.11994402Z
OS Type: linux
OS Architecture: amd64
Go routines: 11
Go version (build): go1.9.2
Uptime: 2m34.699442174s
User ID: 1
User email: admin@sshportal
Version: 1.7.1
GIT SHA: 2555c478b484c6b420c586c2c2a53b22445e3f7f
GIT Branch: HEAD
GIT Tag: v1.7.1
```
installed in docker

** Tracebacks**:
```
2018/03/04 16:02:15 info: shell session  {"args":["ls"],"interactive":true}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x7975fb]

goroutine 140 [running]:
main.shell.func41(0xc420547760, 0x0, 0xc420547760)
	/go/src/github.com/moul/sshportal/shell.go:1886 +0x61b
github.com/moul/sshportal/vendor/github.com/urfave/cli.HandleAction(0x91de20, 0xc4202291d0, 0xc420547760, 0xc42004d600, 0x0)
	/go/src/github.com/moul/sshportal/vendor/github.com/urfave/cli/app.go:502 +0xd2
github.com/moul/sshportal/vendor/github.com/urfave/cli.Command.Run(0x99b2ca, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x9a36cf, 0xe, 0x0, ...)
	/go/src/github.com/moul/sshportal/vendor/github.com/urfave/cli/command.go:210 +0xaad
github.com/moul/sshportal/vendor/github.com/urfave/cli.(*App).RunAsSubcommand(0xc4200f0a80, 0xc4205474a0, 0x0, 0x0)
	/go/src/github.com/moul/sshportal/vendor/github.com/urfave/cli/app.go:383 +0xad7
github.com/moul/sshportal/vendor/github.com/urfave/cli.Command.startApp(0x99f15b, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x9a4b23, 0x10, 0x0, ...)
	/go/src/github.com/moul/sshportal/vendor/github.com/urfave/cli/command.go:298 +0x944
github.com/moul/sshportal/vendor/github.com/urfave/cli.Command.Run(0x99f15b, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x9a4b23, 0x10, 0x0, ...)
	/go/src/github.com/moul/sshportal/vendor/github.com/urfave/cli/command.go:98 +0x136a
github.com/moul/sshportal/vendor/github.com/urfave/cli.(*App).Run(0xc4200f0700, 0xc4202fb320, 0x3, 0x3, 0x0, 0x0)
	/go/src/github.com/moul/sshportal/vendor/github.com/urfave/cli/app.go:259 +0x740
main.shell(0xe14280, 0xc420265d90, 0xc4200ecbb8, 0x5)
	/go/src/github.com/moul/sshportal/shell.go:1935 +0x59d7
main.shellHandler(0xe14280, 0xc420265d90)
	/go/src/github.com/moul/sshportal/ssh.go:211 +0x696
github.com/moul/sshportal/vendor/github.com/gliderlabs/ssh.(*session).handleRequests.func1(0xc420265d90)
	/go/src/github.com/moul/sshportal/vendor/github.com/gliderlabs/ssh/session.go:219 +0x3b
created by github.com/moul/sshportal/vendor/github.com/gliderlabs/ssh.(*session).handleRequests
	/go/src/github.com/moul/sshportal/vendor/github.com/gliderlabs/ssh/session.go:218 +0x216
```

**Comment by cnf** [comment] 2018-03-07 00:35
Still happens with the :latest tag on docker hub as of this evening.

**Comment by jle64** [comment] 2018-03-07 10:46
I have the same issue here and FWIW it seems it only happens in clustered mode with multiple sshportal instances sharing the same database.

**Comment by adyxax** [comment] 2018-03-22 13:56
This was fixed in ([#54](https://github.com/moul/sshportal/pull/54)) by [@jle64](https://github.com/jle64).

**Comment by jle64** [comment] 2018-03-22 14:00
@adyxax : I'm not sure of this, my stacktrace was different than this one that's why I didn't link the PR #54 to this issue.

**Comment by moul** [comment] 2018-04-03 09:48
I just gave a new trial and cannot reproduce the error,

By reading the stack trace, I noticed the version running while you created the post is not up to date:

```
	/go/src/github.com/moul/sshportal/shell.go:1886 +0x61b
```

-> https://github.com/moul/sshportal/blob/master/shell.go#L1886

---

Can you double-check that you are using the latest version (maybe flush some cache before) and try again?

If you still have the error, I would love some more context or an updated stack trace

**Comment by cnf** [comment] 2018-04-25 08:55
just checked with 1.8.0+dev, and `session ls` works now

**Comment by cnf** [comment] 2018-05-03 10:42
and now i get 

```
config> session ls
error: too many SQL variables
```

**Comment by moul** [comment] 2020-09-15 16:34
Closing the issue as I plan to work on the v2 of this project and I need to make some cleanup in the issues see #210

**Closed by moul** 2020-09-15 16:34 UTC
Labels: bug
